name: kas_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+5

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  share_plus: ^7.0.2
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  dio: ^5.4.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.2.18
  flutter_launcher_icons: ^0.12.0
  intl: ^0.17.0
  parse_server_sdk_flutter: ^7.0.0
  image_picker: ^1.0.7
  universal_platform: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.1.1
  hive_generator: ^1.1.0

flutter_native_splash:
  color: "#FFFFFF" #backgound color
  image: assets/splash_web.png
  web: true

# flutter_icons:
#   image_path: "assets/icon.png"
#   ios: true
#   web: 
#     generate: true
#   remove_alfha_ios: true
#   android: "launcher_icon"
#   adaptive_icon_background: "#FFFFFF"
#   adaptive_icon_foreground: "assets/icon.png"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

